#:schema https://kjanat.github.io/runner/schemas/runner.toml.schema.json

[chain]
on_fail = "wait"

[install]
frozen = false
tools  = true

[output]
warnings = true
errors   = true
summary  = true
progress = true
groups   = true
timing   = true

[tasks."bench"]
pm     = "uv"
source = "pyproject.toml"
output = { progress = false }
