[package]
name              = "shellcheck-core"
version.workspace = true
edition.workspace = true
description       = "ShellCheck's checking core, compiled from GHC Core to Rust"
license.workspace = true
publish           = false

[build-dependencies]
anyhow.workspace        = true
h2r-build.workspace     = true
h2r-core-ir.workspace   = true
h2r-lower.workspace     = true
hs-entry.workspace      = true
hs-libraries.workspace  = true
hs-shellcheck.workspace = true

[lints]
workspace = true
