//! Port of `ShellCheck.Data`: the shared word lists and small tables the
//! parser, the analyzer library and the checks all consult.

use crate::interface::Shell;

/// `internalVariables`.
pub(crate) const INTERNAL_VARIABLES: &[&str] = &[
    "",
    "_",
    "rest",
    "REST",
    "CDPATH",
    "ENV",
    "FCEDIT",
    "HISTFILE",
    "HISTSIZE",
    "HOME",
    "IFS",
    "LANG",
    "LC_ALL",
    "LC_COLLATE",
    "LC_CTYPE",
    "LC_MESSAGES",
    "LC_MONETARY",
    "LC_NUMERIC",
    "LC_TIME",
    "MAIL",
    "MAILCHECK",
    "MAILPATH",
    "OLDPWD",
    "OPTARG",
    "OPTIND",
    "PATH",
    "PWD",
    "BASH",
    "BASHOPTS",
    "BASHPID",
    "BASH_ALIASES",
    "BASH_ARGC",
    "BASH_ARGV",
    "BASH_ARGV0",
    "BASH_CMDS",
    "BASH_COMMAND",
    "BASH_EXECUTION_STRING",
    "BASH_LINENO",
    "BASH_LOADABLES_PATH",
    "BASH_REMATCH",
    "BASH_SOURCE",
    "BASH_SUBSHELL",
    "BASH_VERSINFO",
    "BASH_VERSION",
    "COMP_CWORD",
    "COMP_KEY",
    "COMP_LINE",
    "COMP_POINT",
    "COMP_TYPE",
    "COMP_WORDBREAKS",
    "COMP_WORDS",
    "COPROC",
    "DIRSTACK",
    "EPOCHREALTIME",
    "EPOCHSECONDS",
    "EUID",
    "FUNCNAME",
    "GROUPS",
    "HISTCMD",
    "HOSTNAME",
    "HOSTTYPE",
    "MACHTYPE",
    "MAPFILE",
    "OSTYPE",
    "PIPESTATUS",
    "RANDOM",
    "READLINE_ARGUMENT",
    "READLINE_LINE",
    "READLINE_MARK",
    "READLINE_POINT",
    "REPLY",
    "SECONDS",
    "SHELLOPTS",
    "SHLVL",
    "SRANDOM",
    "UID",
    "BASH_COMPAT",
    "BASH_ENV",
    "BASH_XTRACEFD",
    "CHILD_MAX",
    "COLUMNS",
    "COMPREPLY",
    "EMACS",
    "EXECIGNORE",
    "FIGNORE",
    "FUNCNEST",
    "GLOBIGNORE",
    "HISTCONTROL",
    "HISTFILESIZE",
    "HISTIGNORE",
    "HISTTIMEFORMAT",
    "HOSTFILE",
    "IGNOREEOF",
    "INPUTRC",
    "INSIDE_EMACS",
    "LINES",
    "OPTERR",
    "POSIXLY_CORRECT",
    "PROMPT_COMMAND",
    "PROMPT_DIRTRIM",
    "PS0",
    "PS1",
    "PS2",
    "PS3",
    "PS4",
    "SHELL",
    "TIMEFORMAT",
    "TMOUT",
    "BASH_MONOSECONDS",
    "BASH_TRAPSIG",
    "GLOBSORT",
    "auto_resume",
    "histchars",
    "USER",
    "TZ",
    "TERM",
    "LOGNAME",
    "LD_LIBRARY_PATH",
    "LANGUAGE",
    "DISPLAY",
    "HOSTNAME",
    "KRB5CCNAME",
    "LINENO",
    "PPID",
    "TMPDIR",
    "XAUTHORITY",
    ".sh.version",
    "FLAGS_ARGC",
    "FLAGS_ARGV",
    "FLAGS_ERROR",
    "FLAGS_FALSE",
    "FLAGS_HELP",
    "FLAGS_PARENT",
    "FLAGS_RESERVED",
    "FLAGS_TRUE",
    "FLAGS_VERSION",
    "flags_error",
    "flags_return",
    "stderr",
    "stderr_lines",
];

/// `specialIntegerVariables`.
pub(crate) const SPECIAL_INTEGER_VARIABLES: &[&str] = &["$", "?", "!", "#"];

/// `specialVariablesWithoutSpaces`: `"-" : specialIntegerVariables`.
pub(crate) const SPECIAL_VARIABLES_WITHOUT_SPACES: &[&str] = &["-", "$", "?", "!", "#"];

/// `variablesWithoutSpaces`: `specialVariablesWithoutSpaces ++ [..]`.
pub(crate) const VARIABLES_WITHOUT_SPACES: &[&str] = &[
    "-",
    "$",
    "?",
    "!",
    "#",
    "BASHPID",
    "BASH_ARGC",
    "BASH_LINENO",
    "BASH_SUBSHELL",
    "EUID",
    "EPOCHREALTIME",
    "EPOCHSECONDS",
    "LINENO",
    "OPTIND",
    "PPID",
    "RANDOM",
    "READLINE_ARGUMENT",
    "READLINE_MARK",
    "READLINE_POINT",
    "SECONDS",
    "SHELLOPTS",
    "SHLVL",
    "SRANDOM",
    "UID",
    "COLUMNS",
    "HISTFILESIZE",
    "HISTSIZE",
    "LINES",
    "BASH_MONOSECONDS",
    "BASH_TRAPSIG",
    "FLAGS_ERROR",
    "FLAGS_FALSE",
    "FLAGS_TRUE",
];

/// `commonCommands`.
pub(crate) const COMMON_COMMANDS: &[&str] = &[
    "admin",
    "alias",
    "ar",
    "asa",
    "at",
    "awk",
    "basename",
    "batch",
    "bc",
    "bg",
    "break",
    "c99",
    "cal",
    "cat",
    "cd",
    "cflow",
    "chgrp",
    "chmod",
    "chown",
    "cksum",
    "cmp",
    "colon",
    "comm",
    "command",
    "compress",
    "continue",
    "cp",
    "crontab",
    "csplit",
    "ctags",
    "cut",
    "cxref",
    "date",
    "dd",
    "delta",
    "df",
    "diff",
    "dirname",
    "dot",
    "du",
    "echo",
    "ed",
    "env",
    "eval",
    "ex",
    "exec",
    "exit",
    "expand",
    "export",
    "expr",
    "fc",
    "fg",
    "file",
    "find",
    "fold",
    "fuser",
    "gencat",
    "get",
    "getconf",
    "getopts",
    "gettext",
    "grep",
    "hash",
    "head",
    "iconv",
    "ipcrm",
    "ipcs",
    "jobs",
    "join",
    "kill",
    "lex",
    "link",
    "ln",
    "locale",
    "localedef",
    "logger",
    "logname",
    "lp",
    "ls",
    "m4",
    "mailx",
    "make",
    "man",
    "mesg",
    "mkdir",
    "mkfifo",
    "more",
    "msgfmt",
    "mv",
    "newgrp",
    "ngettext",
    "nice",
    "nl",
    "nm",
    "nohup",
    "od",
    "paste",
    "patch",
    "pathchk",
    "pax",
    "pr",
    "printf",
    "prs",
    "ps",
    "pwd",
    "read",
    "readlink",
    "readonly",
    "realpath",
    "renice",
    "return",
    "rm",
    "rmdel",
    "rmdir",
    "sact",
    "sccs",
    "sed",
    "set",
    "sh",
    "shift",
    "sleep",
    "sort",
    "split",
    "strings",
    "strip",
    "stty",
    "tabs",
    "tail",
    "talk",
    "tee",
    "test",
    "time",
    "timeout",
    "times",
    "touch",
    "tput",
    "tr",
    "trap",
    "tsort",
    "tty",
    "type",
    "ulimit",
    "umask",
    "unalias",
    "uname",
    "uncompress",
    "unexpand",
    "unget",
    "uniq",
    "unlink",
    "unset",
    "uucp",
    "uudecode",
    "uuencode",
    "uustat",
    "uux",
    "val",
    "vi",
    "wait",
    "wc",
    "what",
    "who",
    "write",
    "xargs",
    "xgettext",
    "yacc",
    "zcat",
];

/// `sampleWords`.
pub(crate) const SAMPLE_WORDS: &[&str] = &[
    "alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel", "india", "juliett",
    "kilo", "lima", "mike", "november", "oscar", "papa", "quebec", "romeo", "sierra", "tango",
    "uniform", "victor", "whiskey", "xray", "yankee", "zulu",
];

/// `arithmeticBinaryTestOps`.
pub(crate) const ARITHMETIC_BINARY_TEST_OPS: &[&str] = &["-eq", "-ne", "-lt", "-le", "-gt", "-ge"];

/// `ShellCheck.Data.binaryTestOps`.
pub(crate) const BINARY_TEST_OPS: &[&str] = &[
    "-nt", "-ot", "-ef", "==", "!=", "<=", ">=", "-eq", "-ne", "-lt", "-le", "-gt", "-ge", "=~",
    ">", "<", "=", "\\<", "\\>", "\\<=", "\\>=",
];

/// `flagsForRead`.
pub(crate) const FLAGS_FOR_READ: &str = "sreu:n:N:i:p:a:t:";

/// `flagsForMapfile`.
pub(crate) const FLAGS_FOR_MAPFILE: &str = "d:n:O:s:u:C:c:t";

/// `declaringCommands`.
pub(crate) const DECLARING_COMMANDS: &[&str] =
    &["local", "declare", "export", "readonly", "typeset", "let"];

/// `privilegeElevationCommands`.
pub(crate) const PRIVILEGE_ELEVATION_COMMANDS: &[&str] = &["sudo", "doas", "run0"];

/// `shellForExecutable`.
pub(crate) fn shell_for_executable(name: &str) -> Option<Shell> {
    Some(match name {
        "sh" => Shell::Sh,
        "bash" => Shell::Bash,
        "bats" => Shell::Bash,
        "busybox" => Shell::BusyboxSh,
        "busybox sh" => Shell::BusyboxSh,
        "busybox ash" => Shell::BusyboxSh,
        "dash" => Shell::Dash,
        "ash" => Shell::Dash,
        "ksh" => Shell::Ksh,
        "ksh88" => Shell::Ksh,
        "ksh93" => Shell::Ksh,
        "oksh" => Shell::Ksh,
        _ => return None,
    })
}
