[package]
name              = "rshellcheck"
version.workspace = true
edition.workspace = true
license           = "GPL-3.0-only"
publish           = false

[dependencies]
clap.workspace            = true
libc.workspace            = true
mimalloc.workspace        = true
shellcheck-core.workspace = true

[lints]
workspace = true
